### PR TITLE
Feedback changes and fixes

### PR DESCRIPTION
**Pull request by wniestroj**
Simulations sidebar - no layout options selected by default
Simulations sidebar - selecting both layouts deselects both options
Navigation - Fix pkpd version overlap navigation buttons on high scales
Simulation page - fix plots get smaller after each resize/sidebar collapse; Fix height of plots on ultra wide resolutions; Fix simulation Sidebar view for high scales
Simulation page - fix plots box having wrong dimensions on first plot render
Global - Input width and table height adjustments for scales up to 200%
Project page - Disable edit button on shared projects
Simulation page - Add confirmation box to removing plot

### CODE REVIEW

**Review by eatyourgreens — CHANGES_REQUESTED** [review]
I can see the toolbar for simulation plots now, but it's missing the option to edit the plot axes.

A plot of simulation output, with a legend and the plot toolbar. The toolbar has controls to zoom and reset the plot axes, but no option to edit the axes.

Here's production (on the main branch.) The toolbar should have options to reset the axes, edit the axes, and remove the plot. It might also be worth checking the new design with plots that have y-axes defined for both the left and righthand sides of the plot. I think the new container might cut off the righthand y-axis.

The plot toolbar in production, including options to reset the axes, edit the axes, and delete the plot.

**Comment by wniestroj** [comment]
@eatyourgreens I struggled to find this case, however, I believe I have. What I found is that for wide viewports (over 2500 width), when there are supposed to be three columns, but only two plots are displayed, the widths or the positioning of plots was off making the plots overlap. I have refactored it so that there cannot be more columns then plots - so if only one plot is displayed, there will be only one column, two columns for two plots

**Comment by eatyourgreens** [comment]
@wniestroj I can still see the bug on a screen with four plots. Zooming out, then back in again, fixes it.


https://github.com/user-attachments/assets/2ab675f4-e0eb-4032-845c-a96f832de24e

**Review by eatyourgreens — APPROVED** [review]

**Comment by eatyourgreens** [comment]
Happy for this to be merged, though, if you want to look at the plot width separately.

**Comment by wniestroj** [comment]
@eatyourgreens Could you provide me with a path to recreate a view with horizontal scroll visible for the four plots? In this merge request I have added a useEffect that is triggered whenever the number of the plots changes, firing up the resize event. This should resize the plots whenever a plot is added/removed, but for me it always sets the correct width whenever the plots are rendered for the first time as well and I wasn't able to recreate this issue.

I have added additional dependencies to that useEffect for data length and model, hopefully it should fix this issue. Would you be able to retest it, as I cannot recreate this issue?

**Comment by eatyourgreens** [comment]
@wniestroj I'm not seeing that bug now.All I've been doing is loading the app, selecting a project, then opening the Simulations tab.


https://github.com/user-attachments/assets/9acfa9a5-b697-4f51-a6f5-c166f9dcbde6

**Comment by wniestroj** [comment]
@eatyourgreens Awesome, glad to hear that. On another note - on the last video it seems like the scroll from the project's page is overflowing the viewport creating a scroll on the whole page - is that correct, or is this just an issue when recording a screen (I have similar issue whenever I'm recording the screen). If the scroll if overflowing - could you provide me with your resolution and the scale of your browser, so that I could reproduce this issue?

**Comment by eatyourgreens** [comment]
That scroll is always there, even if I'm not recording the screen. I'm on a fairly wide display: 1920 by 1080.

**Pull request merged**
