### PR TITLE
I41 bootstrap

### LINKED ISSUE #41: Use bootstrap 4 to make app useable cross platforms
At the moment the design of the app is largely inspired by a template from http://html5up.net. The resulting app looks nice on a standard screen, and on some smaller screen sizes, but it's not ideal. In addition, the HTML5UP template uses an awful lot of css specifications to define HTML elements, which makes it more difficult to style future elements.

This issue is about using bootstrap 4 to define the layout of the app and also rely more on the bootstrap defined styles. We will still have some customised HTML elements and classes, but hopefully less than now. This refactoring will be useful for the further development of the app and shouldn't be pushed to far into the future.

### PR DESCRIPTION
**Pull request by DavAug**
Closes #41.

Using bootstrap 4 the app is now also mobile pleasant to use (except the temporary plotly figures are not yet super nice). I would suggest that we tackle that when we implement the dash apps properly.

### CODE REVIEW

**Comment by DavAug** [comment]
@martinjrobins 

Hi Martin everything seems to work when I check the app manually, however the test of the password reset workflow weirdly fails

```
Run python pkpdapp/manage.py test pkpdapp
Creating test database for alias 'default'...
......WARNING:django.request:Not Found: /pkpdapp-team/pkpdapp)
F..............
System check identified no issues (0 silenced).
======================================================================
FAIL: test_password_reset_workflow (pkpdapp.tests.test_views.TestRegistrationViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pkpdapp/pkpdapp/pkpdapp/pkpdapp/tests/test_views.py", line 153, in test_password_reset_workflow
    self.assertEquals(response.status_code, 200)
AssertionError: 404 != 200
```

I don't think I've changed anything with the log in workflow and it seems to me that this should be independent of the html layout anyway. Would you know what is going wrong?

**Review by martinjrobins — APPROVED** [review]
looks great @DavAug! Only thing I would say is that you've removed the signed in user's name in the header, but we can add that later if we want

**Comment by martinjrobins** [comment]
oh, and I fixed that bug as well with the test

**Comment by DavAug** [comment]
Thank you so much for reviewing @martinjrobins !

**Comment by martinjrobins** [comment]
yay, automatic deployment went off without a hitch :)

**Pull request merged**
