### PR TITLE
Pkpdx 31 Project page

### PR DESCRIPTION
**Pull request by wniestroj**
image
image
image

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I'm not sure if this is a bug, but whenever I sort the project table, a 'Success' notification pops up on the right. It's very annoying.


https://github.com/user-attachments/assets/467e0e0f-bedc-429d-a880-7dd6b8f5dc9f

**Comment by wniestroj** [comment]
@eatyourgreens Oh, nice catch - I will remove this before merging this MR. Sorting must not be used often if that wasn't caught earlier, as it actually wasn't introduced in this MR :)

**Comment by eatyourgreens** [comment]
@wniestroj Thanks! Yes, I only realised, after reviewing this, that sorting already does this in the production app.

**Comment by wniestroj** [comment]
@eatyourgreens Notification has been removed from sorting

**Pull request merged**
