### PR TITLE
Simulation dashboard

### PR DESCRIPTION
**Pull request by DavAug**
This is the first outline of how the simulate pipeline could look like.

There is no functionality just some new animations and examples of plotly visualisations.

### CODE REVIEW

**Comment by DavAug** [comment]
@gjibooth What do you mean? Are the tiles not all in the same line? The positioning of the tiles is adjusted with the size of the window, but they should be all in a line for if you open it fullscreen

**Comment by gjibooth** [comment]
When full screen on my laptop screen, they are all aligned. When open full screen on my monitor, the buttons are in a 2x2 grid arrangement. Also, the home screen has two buttons on the top and one on the bottom when viewed on my monitor, but are all aligned on my laptop screen

**Comment by DavAug** [comment]
hmm, has your monitor a lower resolution than your laptop?

**Comment by gjibooth** [comment]
Nope - Laptop is 1366 x 768, monitor is 2560 x1140

**Comment by DavAug** [comment]
Hmm let's figure the configs out when I also have a screen of that resolution.

**Pull request merged**
