### PR TITLE
PKPDX 34

### PR DESCRIPTION
**Pull request by wniestroj**

### CODE REVIEW

**Review by eatyourgreens — APPROVED** [review]
Looks good.

One small problem: The form validation error messages are cut off by the container box height now.

The time intervals form, with an invalid value in the last row. The error messages for the invalid values are cut off, so that only the top of each letter can be seen.

**Comment by wniestroj** [comment]
@eatyourgreens Is the scroll not popping up? I'm struggling to recreate such case - for me either the container height increases, making space to display the error message, or if after adding the error message the max height is exceeded, the scroll shows up. Could you provide me with your resolution and scales?
[error.webm](https://github.com/user-attachments/assets/1640a3c8-2296-4624-9236-f848013cec1e)

**Comment by eatyourgreens** [comment]
You can scroll the container down, but you probably shouldn't have to scroll down to see the error essage. A little more vertical padding at the bottom might be useful.

**Comment by wniestroj** [comment]
@eatyourgreens I assumed that as the input has the border changed to red indicating an error, that shouldn't be a problem, however I see your point. Let's merge this one, so that the Model page can be tested and I will fix that issue with other fixes

**Pull request merged**
