### PR TITLE
I30 simulation placeholder

### LINKED ISSUE #30: Better simulation workflow placeholder
This is just a quick fix for the software presentation. I will replace the place holder by a functional data / simulation plot with a slider for the model parameters. At this point it's just hard coded for this one problem, but if time allows we can improve on this also already for the presentation.

I am going to copy from my ErlotinibGefitinib repo 

https://nbviewer.jupyter.org/github/DavAug/ErlotinibGefitinib/blob/master/notebooks/lung_cancer/control_growth/structural_model.ipynb.

### PR DESCRIPTION
**Pull request by DavAug**
Closes #30 .

I inserted a quick fix for simulation of untreated tumour growth as a place holder in the simulation tab, and separated the view into one model building view, and a simulation view.

### CODE REVIEW

**Comment by DavAug** [comment]
@martinjrobins 

There are no tests because this is going to be replaced as soon as we do this properly.

Let me know what you think.

**Comment by martinjrobins** [comment]
I tried to run this branch, but got this error on running the server:

```
Traceback (most recent call last):
  File "/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim/__init__.py", line 196, in _compile
    str('--inplace'),
  File "/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Compiler output:
    running build_ext
    building 'myokit_sim_2_8086969932010761728' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/tmp
    creating build/temp.linux-x86_64-3.6/tmp/tmp_pm0ccg5myokit
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/opt/local/include -I/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim -I/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim -I/home/mrobins/git/pkpdapp/env/include -I/usr/include/python3.6m -c /tmp/tmp_pm0ccg5myokit/source.c -o build/temp.linux-x86_64-3.6/tmp/tmp_pm0ccg5myokit/source.o
    /tmp/tmp_pm0ccg5myokit/source.c:6:10: fatal error: cvode/cvode.h: No such file or directory
     #include <cvode/cvode.h>
              ^~~~~~~~~~~~~~~
    compilation terminated.


```

Looks like a problem with my myokit install, I don't have cvode installed. I've not installed myokit before, any idea @DavAug ?

**Comment by DavAug** [comment]
> I tried to run this branch, but got this error on running the server:
> 
> ```
> Traceback (most recent call last):
>   File "/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim/__init__.py", line 196, in _compile
>     str('--inplace'),
>   File "/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
>     raise SystemExit("error: " + str(msg))
> SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> Compiler output:
>     running build_ext
>     building 'myokit_sim_2_8086969932010761728' extension
>     creating build
>     creating build/temp.linux-x86_64-3.6
>     creating build/temp.linux-x86_64-3.6/tmp
>     creating build/temp.linux-x86_64-3.6/tmp/tmp_pm0ccg5myokit
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/opt/local/include -I/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim -I/home/mrobins/git/pkpdapp/env/lib/python3.6/site-packages/myokit/_sim -I/home/mrobins/git/pkpdapp/env/include -I/usr/include/python3.6m -c /tmp/tmp_pm0ccg5myokit/source.c -o build/temp.linux-x86_64-3.6/tmp/tmp_pm0ccg5myokit/source.o
>     /tmp/tmp_pm0ccg5myokit/source.c:6:10: fatal error: cvode/cvode.h: No such file or directory
>      #include <cvode/cvode.h>
>               ^~~~~~~~~~~~~~~
>     compilation terminated.
> ```
> 
> Looks like a problem with my myokit install, I don't have cvode installed. I've not installed myokit before, any idea @DavAug ?

Yes that's a myokit error - unfortunately myokit needs sundials to be installed in order to run and the error message complains that it can't find cvode from sundials. So you will have to install sundials on your machine with something like `apt get install libsundials-dev`. You can check the workflows for the command.

**Comment by martinjrobins** [comment]
> apt-get install libsundials-dev

that is a shame, gonna make the readme a lot more convoluted,  we'll have to decide if we want to support windows/mac installation or not

**Review by martinjrobins — CHANGES_REQUESTED** [review]
looks great, make a good placeholder for the time being. Can you add a line to the readme about installing sundials in ubuntu?

**Comment by DavAug** [comment]
@martinjrobins 

Thanks! I added the instructions to the README. I think we should aim to containerise the app, so people will only have to start the container eventually. And once we have the app running on Heroku nobody really needs to install the app except for the developers. 

What do you think?

**Comment by martinjrobins** [comment]
yup, would be good to use docker. I'll open an issue on that

**Review by martinjrobins — APPROVED** [review]

**Pull request merged**
