### PR TITLE
Issue 112 pk models

### LINKED ISSUE #112: add new pk models to database
sbml files are in #106

### PR DESCRIPTION
**Pull request by martinjrobins**
- adds one, two and three compartment pk models
- changes simulation dash app to show all outputs

Fixes #112

### CODE REVIEW

**Review by ben18785 — CHANGES_REQUESTED** [review]
Looks good! One thing I wondered was, when you select the "Dose compartment" when you do "Create model", what were the acceptable options here? Obviously,  "central" works fine but when you fill in something else (I tried "peripheral") I then got a server error. Could we restrict these options (e.g. through a dropdown rather than a free text input) so as to avoid this?

**Comment by martinjrobins** [comment]
> Looks good! One thing I wondered was, when you select the "Dose compartment" when you do "Create model", what were the acceptable options here? Obviously, "central" works fine but when you fill in something else (I tried "peripheral") I then got a server error. Could we restrict these options (e.g. through a dropdown rather than a free text input) so as to avoid this?

Yea, I think this would be useful to add. I'll put it in

**Comment by martinjrobins** [comment]
> Yea, I think this would be useful to add. I'll put it in

Ok, I added this. Its not truely dynamic, as the choices are always 'central', 'peripheral' and 'peripheral2', but it does show an error if the chosen compartment does not exist in the model.  it will do for now until we redo the UI in javascript.

**Review by ben18785 — APPROVED** [review]
Looks good -- happy to merge

**Pull request merged**
